/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as KaryaIndexRouteImport } from './routes/karya.index'
import { Route as KaryaIdRouteImport } from './routes/karya.$id'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellKaryaIndexRouteImport } from './routes/admin/_shell/karya/index'
import { Route as AdminShellKaryaTambahRouteImport } from './routes/admin/_shell/karya/tambah'
import { Route as AdminShellKategoriIndexRouteImport } from './routes/admin/_shell/kategori/index'
import { Route as AdminShellPesertaIndexRouteImport } from './routes/admin/_shell/peserta/index'
import { Route as AdminShellPesertaTambahRouteImport } from './routes/admin/_shell/peserta/tambah'
import { Route as AdminShellKaryaIdEditRouteImport } from './routes/admin/_shell/karya/$id.edit'
import { Route as AdminShellPesertaIdEditRouteImport } from './routes/admin/_shell/peserta/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryaIndexRoute = KaryaIndexRouteImport.update({
  id: '/karya/',
  path: '/karya/',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryaIdRoute = KaryaIdRouteImport.update({
  id: '/karya/$id',
  path: '/karya/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellKaryaIndexRoute = AdminShellKaryaIndexRouteImport.update({
  id: '/karya/',
  path: '/karya/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellKaryaTambahRoute = AdminShellKaryaTambahRouteImport.update({
  id: '/karya/tambah',
  path: '/karya/tambah',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellKategoriIndexRoute = AdminShellKategoriIndexRouteImport.update({
  id: '/kategori/',
  path: '/kategori/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPesertaIndexRoute = AdminShellPesertaIndexRouteImport.update({
  id: '/peserta/',
  path: '/peserta/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPesertaTambahRoute = AdminShellPesertaTambahRouteImport.update({
  id: '/peserta/tambah',
  path: '/peserta/tambah',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellKaryaIdEditRoute = AdminShellKaryaIdEditRouteImport.update({
  id: '/karya/$id/edit',
  path: '/karya/$id/edit',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPesertaIdEditRoute = AdminShellPesertaIdEditRouteImport.update({
  id: '/peserta/$id/edit',
  path: '/peserta/$id/edit',
  getParentRoute: () => AdminShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/karya/$id': typeof KaryaIdRoute
  '/karya/': typeof KaryaIndexRoute
  '/admin/': typeof AdminShellIndexRoute
  '/admin/karya/tambah': typeof AdminShellKaryaTambahRoute
  '/admin/peserta/tambah': typeof AdminShellPesertaTambahRoute
  '/admin/karya/': typeof AdminShellKaryaIndexRoute
  '/admin/kategori/': typeof AdminShellKategoriIndexRoute
  '/admin/peserta/': typeof AdminShellPesertaIndexRoute
  '/admin/karya/$id/edit': typeof AdminShellKaryaIdEditRoute
  '/admin/peserta/$id/edit': typeof AdminShellPesertaIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/karya/$id': typeof KaryaIdRoute
  '/karya': typeof KaryaIndexRoute
  '/admin': typeof AdminShellIndexRoute
  '/admin/karya/tambah': typeof AdminShellKaryaTambahRoute
  '/admin/peserta/tambah': typeof AdminShellPesertaTambahRoute
  '/admin/karya': typeof AdminShellKaryaIndexRoute
  '/admin/kategori': typeof AdminShellKategoriIndexRoute
  '/admin/peserta': typeof AdminShellPesertaIndexRoute
  '/admin/karya/$id/edit': typeof AdminShellKaryaIdEditRoute
  '/admin/peserta/$id/edit': typeof AdminShellPesertaIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/karya/$id': typeof KaryaIdRoute
  '/karya/': typeof KaryaIndexRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
  '/admin/_shell/karya/tambah': typeof AdminShellKaryaTambahRoute
  '/admin/_shell/peserta/tambah': typeof AdminShellPesertaTambahRoute
  '/admin/_shell/karya/': typeof AdminShellKaryaIndexRoute
  '/admin/_shell/kategori/': typeof AdminShellKategoriIndexRoute
  '/admin/_shell/peserta/': typeof AdminShellPesertaIndexRoute
  '/admin/_shell/karya/$id/edit': typeof AdminShellKaryaIdEditRoute
  '/admin/_shell/peserta/$id/edit': typeof AdminShellPesertaIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/karya/$id'
    | '/karya/'
    | '/admin/'
    | '/admin/karya/tambah'
    | '/admin/peserta/tambah'
    | '/admin/karya/'
    | '/admin/kategori/'
    | '/admin/peserta/'
    | '/admin/karya/$id/edit'
    | '/admin/peserta/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/karya/$id'
    | '/karya'
    | '/admin'
    | '/admin/karya/tambah'
    | '/admin/peserta/tambah'
    | '/admin/karya'
    | '/admin/kategori'
    | '/admin/peserta'
    | '/admin/karya/$id/edit'
    | '/admin/peserta/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/_shell'
    | '/admin/login'
    | '/karya/$id'
    | '/karya/'
    | '/admin/_shell/'
    | '/admin/_shell/karya/tambah'
    | '/admin/_shell/peserta/tambah'
    | '/admin/_shell/karya/'
    | '/admin/_shell/kategori/'
    | '/admin/_shell/peserta/'
    | '/admin/_shell/karya/$id/edit'
    | '/admin/_shell/peserta/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  KaryaIdRoute: typeof KaryaIdRoute
  KaryaIndexRoute: typeof KaryaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karya/': {
      id: '/karya/'
      path: '/karya'
      fullPath: '/karya/'
      preLoaderRoute: typeof KaryaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karya/$id': {
      id: '/karya/$id'
      path: '/karya/$id'
      fullPath: '/karya/$id'
      preLoaderRoute: typeof KaryaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/karya/': {
      id: '/admin/_shell/karya/'
      path: '/karya'
      fullPath: '/admin/karya/'
      preLoaderRoute: typeof AdminShellKaryaIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/karya/tambah': {
      id: '/admin/_shell/karya/tambah'
      path: '/karya/tambah'
      fullPath: '/admin/karya/tambah'
      preLoaderRoute: typeof AdminShellKaryaTambahRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/kategori/': {
      id: '/admin/_shell/kategori/'
      path: '/kategori'
      fullPath: '/admin/kategori/'
      preLoaderRoute: typeof AdminShellKategoriIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/peserta/': {
      id: '/admin/_shell/peserta/'
      path: '/peserta'
      fullPath: '/admin/peserta/'
      preLoaderRoute: typeof AdminShellPesertaIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/peserta/tambah': {
      id: '/admin/_shell/peserta/tambah'
      path: '/peserta/tambah'
      fullPath: '/admin/peserta/tambah'
      preLoaderRoute: typeof AdminShellPesertaTambahRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/karya/$id/edit': {
      id: '/admin/_shell/karya/$id/edit'
      path: '/karya/$id/edit'
      fullPath: '/admin/karya/$id/edit'
      preLoaderRoute: typeof AdminShellKaryaIdEditRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/peserta/$id/edit': {
      id: '/admin/_shell/peserta/$id/edit'
      path: '/peserta/$id/edit'
      fullPath: '/admin/peserta/$id/edit'
      preLoaderRoute: typeof AdminShellPesertaIdEditRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellIndexRoute: typeof AdminShellIndexRoute
  AdminShellKaryaTambahRoute: typeof AdminShellKaryaTambahRoute
  AdminShellPesertaTambahRoute: typeof AdminShellPesertaTambahRoute
  AdminShellKaryaIndexRoute: typeof AdminShellKaryaIndexRoute
  AdminShellKategoriIndexRoute: typeof AdminShellKategoriIndexRoute
  AdminShellPesertaIndexRoute: typeof AdminShellPesertaIndexRoute
  AdminShellKaryaIdEditRoute: typeof AdminShellKaryaIdEditRoute
  AdminShellPesertaIdEditRoute: typeof AdminShellPesertaIdEditRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellIndexRoute: AdminShellIndexRoute,
  AdminShellKaryaTambahRoute: AdminShellKaryaTambahRoute,
  AdminShellPesertaTambahRoute: AdminShellPesertaTambahRoute,
  AdminShellKaryaIndexRoute: AdminShellKaryaIndexRoute,
  AdminShellKategoriIndexRoute: AdminShellKategoriIndexRoute,
  AdminShellPesertaIndexRoute: AdminShellPesertaIndexRoute,
  AdminShellKaryaIdEditRoute: AdminShellKaryaIdEditRoute,
  AdminShellPesertaIdEditRoute: AdminShellPesertaIdEditRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  KaryaIdRoute: KaryaIdRoute,
  KaryaIndexRoute: KaryaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
